# Generated by Django 4.0.6 on 2022-07-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_articulo_imagen_alter_articulo_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
